### PR TITLE
enhance vessel info includes handling, documentation, and response parsing

### LINKED ISSUE #239: `search_type = "id"` failing
@lykmapipo 
- in `gfw_vessel_info()` when `search_type = "id"` we need `includes` to apply to serach_type = 'id' as well , otherwise the search will fail
 
Can you add a correction for this in your sequence of PRs?

```
gfw_vessel_info(ids = "8c7304226-6c71-edbe-0b63-c246734b3c01",
                search_type = "id")
```

### PR DESCRIPTION
**Pull request by lykmapipo**
This:
- Support `search_type`-aware `includes` handling in `gfw_vessel_info()`
- Change `includes` default to `NULL` and derive supported values dynamically based on `search_type`
- Add `validate_gfw_vessel_info_includes()` helper to normalize and validate requested `includes`
- Update `gfw_vessel_info()` documentation to clearly describe supported `includes` per search type
- Refactor includes formatting so it is applied consistently for both `"search"` and `"id"` queries
- Improve response parsing to safely handle missing `registryOwners`, `registryPublicAuthorizations`, and `matchCriteria`
- Closes #239

### CODE REVIEW

File: R/gfw_vessel_info.R [hunk 1]
```diff
@@ -6,12 +7,23 @@
...
 #' \describe{
 #' \item{`"OWNERSHIP"`}{returns ownership information}
-#' \item{`"AUTHORIZATIONS"`}{lists public authorizations for that vessel}
+#' \item{`"AUTHORIZATIONS"`}{lists public authorizations for the vessel}
 #' \item{`"MATCH_CRITERIA"`}{adds information about the reason why a vessel is returned}
 #' }
+#'
+#' When `search_type = "id"`, supported values are:
+#' \describe{
+#' \item{`"POTENTIAL_RELATED_SELF_REPORTED_INFO"`}{returns potential related self-reported information.}
```
Comment (giselamo) [inline R/gfw_vessel_info.R]: Please add more detail: "potential related self-reported information allows to bring all related vessel_ids based on the matching with the registry. It is  Global Fishing Watch best guess to match AIS positions to Vessel Identity information from public registries. See how Vessel API is used in Vessel Viewer here:  https://globalfishingwatch.org/our-apis/assets/2024_Vessel_Viewer_and_APIs_behind_It.pdf

**Review by giselamo — COMMENTED** [review]
Added one improvement

**Review by AndreaSanchezTapia — APPROVED** [review]
